version: '3'
services:
  hello-world:
    container_name: hello-world
    build:
      context: ./
      dockerfile: Dockerfile
    # volumes:
    #   - type: volume
    #     source: hello-volume
    #     target: /app
    entrypoint: sh /tmp/entry.sh
    ports:
      - '3000:3000'

# volumes:
#   hello-volume:
#     name: hello-volume
#     driver: local
#     driver_opts:
#       device: ./app
#       type: none
#       o: bind